version: "3.9"

networks:
  proxy:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    container_name: goat_geoapi
    hostname: goat_geoapi
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5002:5000"
    networks:
      proxy:
