name: "PR"

on:
  pull_request_target:
    branches: [main]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    name: test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release-docker-build:
    name: docker-build
    uses: ./.github/workflows/release.yml
    secrets: inherit

  required:
    needs: [lint, test, release-docker-build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1