name: "Push"

on:
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    name: release
    uses: ./.github/workflows/release.yml
    secrets: inherit
