name: "Release"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐳 Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 🐳 Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: goatcommunity/goat-geoapi
          flavor: |
            latest=auto
          tags: |
            type=raw,value={{sha}}
            type=ref,event=tag,priority=200
            type=raw,value=latest,enable=${{startsWith(github.ref, 'refs/tags/v' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) )}},priority=100,
            type=ref,event=pr,priority=100

      - name: 🐳 Build changed
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🐳 Find the primary image tag we just pushed, and output it
        id: image-tag
        run: |
          echo "image-tag=${{ steps.docker_meta.outputs.version }}" >> $GITHUB_OUTPUT