name: "Test"

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📥 Checkout PR
        uses: goat-community/.github/.github/actions/pr-git-checkout

      - name: 📥 Poetry install
        uses: goat-community/.github/.github/actions/poetry-install
        with:
          cwd: ${{ github.workspace }}

      - name: 🔬 Run tests
        run: poetry run bash scripts/test.sh